### ISSUE TITLE
How to use the SSD framework in paddle 0.10.0 released version?

### ISSUE THREAD

**Issue by TheodoreG** [PaddlePaddle/models#454]
I want to use the object detection framework in models/ssd, but I got those errors:
root@c1b28bac8e39:/home/workspace/models/ssd# python train.py  --use_gpu=True --trainer_count=1
I1113 07:04:48.332365   319 Util.cpp:166] commandline:  --use_gpu=True --trainer_count=4
Traceback (most recent call last):
  File "train.py", line 84, in <module>
    init_model_path='./vgg/vgg_model.tar.gz')
  File "train.py", line 20, in train
    cost, detect_out = vgg_ssd_net.net_conf('train')
  File "/home/workspace/models/ssd/vgg_ssd_net.py", line 242, in net_conf
    detection_out = paddle.layer.detection_output(
AttributeError: 'module' object has no attribute 'detection_output'
root@c1b28bac8e39:/home/workspace/models/ssd#
What should I do?

**Comment by pkuyym** [comment]
请更新你的docker 镜像
